owner: azomics
name: metacyto_glm_all
description: This tool uses MetaCyto to perform a generalized linear model analysis estimating effect size of independent variables.
long_description: |
    **Note**
    This was written by immport-dev-team, only uploaded to the toolshed by azomics user.
    
    **Input**
    This tool requires the output from a MetaCyto clustering analysis, as well as a tabular file containing corresponding metadata (see below for formatting). At least one independent variable must be provided for the generalized linear model.
    The file containing the metadata needs to be formatted according to the example below. Any other formats will not work.
    Parameters
    Variables for GLM
    Independent variables used to run the GLM analysis. These variables need to be in the metadata file headers with corresponding values for each file in each group.
    Confidence Interval
    Value used to set up the confidence threshold for the GLM analysis.
    **Output**
    This tool generates a table describing the overall effect size of the independent variables on provided cluster definitions. A forest plot is optionally produced.
    https://www.immportgalaxy.org
categories:
    - Flow Cytometry Analysis
remote_repository_url: https://github.com/ImmPortDB/immport-galaxy/tree/master/tools/flowtools/pheno_corr
type: unrestricted
